require:
  - rubocop-rspec

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - spec/lib/app_spec.rb
