name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
          bundler-cache: true

      - name: Standard RB
        run: bundle exec standardrb

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ["2.7.8", "3.0", "3.1", "3.2", "3.3", "3.4"]

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: RSpec
        run: bundle exec rspec
