name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ["2.6.8", "2.7.8", "3.0.6", "3.1.4", "3.2.3", "3.3.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: RSpec
        run: bundle exec rspec
